// src/react/ArtifactuseInlineWidget.jsx
// ArtifactuseInlineWidget.jsx
// Inline iframe renderer for registered widget artifacts

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useArtifactuse } from './index';
import {
  clampWidgetHeight,
  getWidgetContainerStyle,
  getWidgetIframeStyle,
  getWidgetSizing,
} from '../core/widgetSizing.js';

function appendWidgetParams(url, params = {}) {
  if (!url) return '';
  try {
    const parsed = new URL(url, window.location.href);
    Object.entries(params).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== '') {
        parsed.searchParams.set(key, value);
      }
    });
    return parsed.toString();
  } catch {
    return url;
  }
}

export default function ArtifactuseInlineWidget({
  artifact,
  theme = 'dark',
  onAction,
  onStateChange,
  onHeightChange,
  onFollowUp,
  pending = false,
  className = '',
}) {
  const { instance } = useArtifactuse();
  const iframeRef = useRef(null);
  const stateRef = useRef(artifact?.widgetState || {});
  const sizing = useMemo(() => getWidgetSizing(artifact?.widget || {}), [artifact?.widget]);
  const [height, setHeight] = useState(sizing.height);
  const [ready, setReady] = useState(false);
  const containerStyle = useMemo(() => getWidgetContainerStyle(sizing), [sizing]);
  const iframeStyle = useMemo(() => getWidgetIframeStyle(height, sizing), [height, sizing]);

  const widgetUrl = artifact?.widget?.url || '';
  const validation = artifact?.validation || { valid: true, errors: [] };

  const iframeSrc = useMemo(() => {
    return appendWidgetParams(widgetUrl, {
      theme,
      template: artifact?.template,
      artifactId: artifact?.id,
    });
  }, [widgetUrl, theme, artifact?.template, artifact?.id]);

  const targetOrigin = '*';

  const payload = useMemo(() => ({
    artifactId: artifact?.id,
    template: artifact?.template,
    props: artifact?.props || {},
    state: stateRef.current,
    actions: artifact?.actions || [],
    permissions: artifact?.permissions || [],
    theme,
    inline: true,
    validation,
  }), [artifact, theme, validation]);

  const postToWidget = useCallback((action, data) => {
    const iframeWindow = iframeRef.current?.contentWindow;
    if (!iframeWindow) return;

    iframeWindow.postMessage({
      type: 'artifactuse',
      action,
      data,
      timestamp: Date.now(),
    }, targetOrigin);
  }, [targetOrigin]);

  const loadWidget = useCallback(() => {
    postToWidget('widget:load', payload);
  }, [payload, postToWidget]);

  useEffect(() => {
    const iframeWindow = iframeRef.current?.contentWindow;

    function handleMessage(event) {
      if (iframeWindow && event.source !== iframeWindow) return;

      const { type, action, data } = event.data || {};
      if (type !== 'artifactuse') return;

      if (action === 'widget:ready' || action === 'ready') {
        setReady(true);
        loadWidget();
        return;
      }

      if (action === 'widget:height') {
        const nextHeight = clampWidgetHeight(data?.height || height, sizing);
        setHeight(nextHeight);
        instance.emit('widget:height', { artifactId: artifact.id, template: artifact.template, height: nextHeight });
        onHeightChange?.({ artifactId: artifact.id, template: artifact.template, height: nextHeight });
        return;
      }

      if (action === 'widget:state') {
        stateRef.current = data?.state || {};
        const eventData = { artifactId: artifact.id, template: artifact.template, state: stateRef.current };
        instance.emit('widget:state', eventData);
        onStateChange?.(eventData);
        return;
      }

      if (action === 'widget:action') {
        const eventData = {
          artifactId: artifact.id,
          template: artifact.template,
          action: data?.action || data?.actionId,
          payload: data?.payload || {},
          props: artifact.props || {},
          state: stateRef.current,
          timestamp: Date.now(),
        };
        instance.emit('widget:action', eventData);
        onAction?.(eventData);
        return;
      }

      if (action === 'widget:followup') {
        const eventData = {
          artifactId: artifact.id,
          template: artifact.template,
          ...data,
        };
        instance.emit('widget:followup', eventData);
        onFollowUp?.(eventData);
      }
    }

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [artifact, height, instance, loadWidget, onAction, onFollowUp, onHeightChange, onStateChange, sizing]);

  useEffect(() => {
    if (ready) loadWidget();
  }, [loadWidget, ready]);

  if (pending && (!validation.valid || !iframeSrc)) {
    return (
      <div className={`artifactuse-inline-widget artifactuse-inline-widget--loading ${className}`.trim()} style={containerStyle}>
        <div className="artifactuse-inline-widget__loading-line" />
        <div className="artifactuse-inline-widget__loading-line artifactuse-inline-widget__loading-line--short" />
      </div>
    );
  }

  if (!validation.valid) {
    return (
      <div className={`artifactuse-inline-widget artifactuse-inline-widget--error ${className}`.trim()} style={containerStyle}>
        <div className="artifactuse-inline-widget__error-title">Widget cannot be rendered</div>
        <ul className="artifactuse-inline-widget__error-list">
          {(validation.errors || []).map(error => <li key={error}>{error}</li>)}
        </ul>
      </div>
    );
  }

  if (!iframeSrc) {
    return (
      <div className={`artifactuse-inline-widget artifactuse-inline-widget--error ${className}`.trim()} style={containerStyle}>
        <div className="artifactuse-inline-widget__error-title">Widget template is not registered</div>
        <div className="artifactuse-inline-widget__error-text">{artifact?.template || 'Unknown template'}</div>
      </div>
    );
  }

  return (
    <div className={`artifactuse-inline-widget ${className}`.trim()} data-widget-template={artifact?.template} style={containerStyle}>
      <iframe
        ref={iframeRef}
        src={iframeSrc}
        title={artifact?.title || artifact?.template || 'Artifactuse widget'}
        className="artifactuse-inline-widget__iframe"
        style={iframeStyle}
        sandbox="allow-scripts allow-forms allow-popups allow-downloads"
        onLoad={() => window.setTimeout(loadWidget, 50)}
      />
    </div>
  );
}

// src/vue/ArtifactuseInlineWidget.vue
<template>
  <div
    v-if="pending && (!isValid || !iframeSrc)"
    class="artifactuse-inline-widget artifactuse-inline-widget--loading"
    :style="containerStyle"
  >
    <div class="artifactuse-inline-widget__loading-line"></div>
    <div class="artifactuse-inline-widget__loading-line artifactuse-inline-widget__loading-line--short"></div>
  </div>

  <div
    v-else-if="!isValid"
    class="artifactuse-inline-widget artifactuse-inline-widget--error"
    :style="containerStyle"
  >
    <div class="artifactuse-inline-widget__error-title">Widget cannot be rendered</div>
    <ul class="artifactuse-inline-widget__error-list">
      <li v-for="error in validationErrors" :key="error">{{ error }}</li>
    </ul>
  </div>

  <div
    v-else-if="!iframeSrc"
    class="artifactuse-inline-widget artifactuse-inline-widget--error"
    :style="containerStyle"
  >
    <div class="artifactuse-inline-widget__error-title">Widget template is not registered</div>
    <div class="artifactuse-inline-widget__error-text">{{ artifact?.template || 'Unknown template' }}</div>
  </div>

  <div
    v-else
    class="artifactuse-inline-widget"
    :data-widget-template="artifact?.template"
    :style="containerStyle"
  >
    <iframe
      ref="iframeRef"
      :src="iframeSrc"
      :title="artifact?.title || artifact?.template || 'Artifactuse widget'"
      class="artifactuse-inline-widget__iframe"
      :style="iframeStyle"
      sandbox="allow-scripts allow-forms allow-popups allow-downloads"
      @load="handleLoad"
    ></iframe>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useArtifactuse } from './index.js';
import {
  clampWidgetHeight,
  getWidgetContainerStyle,
  getWidgetIframeStyle,
  getWidgetSizing,
} from '../core/widgetSizing.js';

const props = defineProps({
  artifact: { type: Object, required: true },
  theme: { type: String, default: 'dark' },
  pending: { type: Boolean, default: false },
});

const emit = defineEmits(['action', 'state-change', 'height-change', 'follow-up']);

const { instance } = useArtifactuse();
const iframeRef = ref(null);
const sizing = computed(() => getWidgetSizing(props.artifact?.widget || {}));
const height = ref(sizing.value.height);
const ready = ref(false);
const widgetState = ref(props.artifact?.widgetState || {});
const containerStyle = computed(() => getWidgetContainerStyle(sizing.value));
const iframeStyle = computed(() => getWidgetIframeStyle(height.value, sizing.value));

const validation = computed(() => props.artifact?.validation || { valid: true, errors: [] });
const isValid = computed(() => validation.value.valid !== false);
const validationErrors = computed(() => validation.value.errors || []);

function appendWidgetParams(url, params = {}) {
  if (!url) return '';
  try {
    const parsed = new URL(url, window.location.href);
    Object.entries(params).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== '') {
        parsed.searchParams.set(key, value);
      }
    });
    return parsed.toString();
  } catch {
    return url;
  }
}

const iframeSrc = computed(() => appendWidgetParams(props.artifact?.widget?.url || '', {
  theme: props.theme,
  template: props.artifact?.template,
  artifactId: props.artifact?.id,
}));

const targetOrigin = computed(() => '*');

const payload = computed(() => ({
  artifactId: props.artifact?.id,
  template: props.artifact?.template,
  props: props.artifact?.props || {},
  state: widgetState.value,
  actions: props.artifact?.actions || [],
  permissions: props.artifact?.permissions || [],
  theme: props.theme,
  inline: true,
  validation: validation.value,
}));

function postToWidget(action, data) {
  const iframeWindow = iframeRef.value?.contentWindow;
  if (!iframeWindow) return;

  iframeWindow.postMessage({
    type: 'artifactuse',
    action,
    data,
    timestamp: Date.now(),
  }, targetOrigin.value);
}

function loadWidget() {
  postToWidget('widget:load', payload.value);
}

function handleLoad() {
  window.setTimeout(loadWidget, 50);
}

function handleMessage(event) {
  const iframeWindow = iframeRef.value?.contentWindow;
  if (iframeWindow && event.source !== iframeWindow) return;

  const { type, action, data } = event.data || {};
  if (type !== 'artifactuse') return;

  if (action === 'widget:ready' || action === 'ready') {
    ready.value = true;
    loadWidget();
    return;
  }

  if (action === 'widget:height') {
    const nextHeight = clampWidgetHeight(data?.height || height.value, sizing.value);
    height.value = nextHeight;
    const eventData = { artifactId: props.artifact.id, template: props.artifact.template, height: nextHeight };
    instance.emit('widget:height', eventData);
    emit('height-change', eventData);
    return;
  }

  if (action === 'widget:state') {
    widgetState.value = data?.state || {};
    const eventData = { artifactId: props.artifact.id, template: props.artifact.template, state: widgetState.value };
    instance.emit('widget:state', eventData);
    emit('state-change', eventData);
    return;
  }

  if (action === 'widget:action') {
    const eventData = {
      artifactId: props.artifact.id,
      template: props.artifact.template,
      action: data?.action || data?.actionId,
      payload: data?.payload || {},
      props: props.artifact.props || {},
      state: widgetState.value,
      timestamp: Date.now(),
    };
    instance.emit('widget:action', eventData);
    emit('action', eventData);
    return;
  }

  if (action === 'widget:followup') {
    const eventData = {
      artifactId: props.artifact.id,
      template: props.artifact.template,
      ...data,
    };
    instance.emit('widget:followup', eventData);
    emit('follow-up', eventData);
  }
}

watch(payload, () => {
  if (ready.value) loadWidget();
});

onMounted(() => {
  window.addEventListener('message', handleMessage);
});

onBeforeUnmount(() => {
  window.removeEventListener('message', handleMessage);
});
</script>
